### ISSUE TITLE
npm zombie 

### ISSUE THREAD

**Issue by Donas4Ceos** [enyojs/enyo#1475]
07:12:14.275Z FATAL enyo-dev: Cannot read property 'length' of undefined
  TypeError: Cannot read property 'length' of undefined
      at ProcessSourceStream._resolved (/usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:223:20)
      at ProcessSourceStream._resolve (/usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:169:8)
      at ProcessSourceStream._dependency (/usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:291:47)
      at /usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:226:17
      at Array.forEach (native)
      at ProcessSourceStream._resolved (/usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:225:18)
      at ProcessSourceStream._resolve (/usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:169:8)
      at ProcessSourceStream._dependency (/usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:291:47)
      at /usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:226:17
      at Array.forEach (native)
      at ProcessSourceStream._resolved (/usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:225:18)
      at ProcessSourceStream._resolve (/usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:169:8)
      at ProcessSourceStream._dependency (/usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:291:47)
      at /usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:226:17
      at Array.forEach (native)
      at ProcessSourceStream._resolved (/usr/local/lib/node_modules/enyo-dev/lib/Packager/lib/process-source-stream/index.js:225:18)

**Comment by ryanjduffy** [comment]
Thanks for the report. Can you elaborate on how this error was caused? A repo/zip that reproduces the issue would be very helpful.

**Comment by Donas4Ceos** [comment]
Zombie, is a node module,I use moonstone 2.7.0 whit enyo 2.7.0, enyo-dev version 1.0.0, 
this is the process to reproduce "FATAL enyo-dev: Cannot read property 'length' of undefined" 
1-  npm install zombie
2- instance zombie -> const Browser = require('zombie'); into a class
3-  enyo pack
4- "FATAL enyo-dev: Cannot read property 'length' of undefined" 

In my first test i run "npm install zombie" into the directory project this install the module into node_modules and add the dependency automatically in package.json in the tag  
"dependencies": {
        "zombie": "^5.0.7"
    } 
next run the command "enyo pack" and get "FATAL enyo-dev: Cannot read property 'length' of undefined" 

In my second test install the node module in my default node_modules folder and copy the module on the project into node_modules folder, "const Browser = require('zombie');"  into a class and run "enyo pack" and get "FATAL enyo-dev: Cannot read property 'length' of undefined"
